# -*- coding: utf-8 -*-
"""python constructor encapsulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rvMGDRo2eDrED0mQ9Tko0LiCmJS9B7lK
"""

class car:

  def __init__(self,brand,model,year):
    self.__brand = brand  #SET PRIVATE
    self.model = model #SET AS PUBLIC
    self.year = year

  def get_brand(self):
    return self.__brand

  def accelaration(self):
    print(f'The car brand is {self.model} in  accelarating !')

#create object for car
my_obj = car("Tesla", "Model A", 2023)

#Access data
print(my_obj.get_brand())

#Access model
print(my_obj.model)

#Access accelaration
my_obj.accelaration()