name: Python Application

on: [push, pull_request]  # Adjusted to trigger on both pushes and pull requests

jobs:
  build:
    runs-on: ubuntu-latest  # Updated to use Ubuntu for cross-platform compatibility

    steps:
    - name: Check out the code
      uses: actions/checkout@v3  # Updated to the latest version

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Updated Python version to 3.12

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run spell7.py
      run: |
        python spell7.py

    - name: Run spell_gram.py
      run: |
        python spell_gram.py
