channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=22.2.2
- pip:
  - mlflow==2.15.1
  - cloudpickle==3.0.0
  - packaging==21.3
  - psutil==5.9.0
  - pyyaml==6.0.2
  - scikit-learn==1.1.1
  - typing-extensions==4.12.2
name: mlflow-env
